version: '3'

services:
  adminer:
    container_name: auth_adminer
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080

  db:
    container_name: auth_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_db
    ports:
      - 5432:5432
